name: Build
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: windows-latest
            rid: win-x86
          - os: macos-latest
            rid: osx-x64
          - os: ubuntu-latest
            rid: linux-x64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: |
          cd src/WPCEmu
          dotnet build WPCEmu.csproj -c Release -r ${{ matrix.rid }}
      - name: Test
        run: |
          cd src/WPCEmu.Test
          dotnet test WPCEmu.Test.csproj --runtime ${{ matrix.rid }} -v n

  dispatch:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.repository == 'jsm174/wpc-emu-cs' && github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          event-type: build-complete
