name: Publish
on:
  repository_dispatch:
    types: [ release-complete ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.commitish }}
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: |
          cd src/WPCEmu
          dotnet pack -c Release -o nupkg
          nuget push nupkg/WPCEmu.*.nupkg -ApiKey ${{ secrets.NUGET_KEY }} -src https://api.nuget.org/v3/index.json
